name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo 
        uses: actions/checkout@v4

      - name: Build the backend image 
        run: | 
          cd backend 
          docker build -t backend:latest . 

      - name: Build the frontend image
        run: | 
          cd frontend 
          docker build -t frontend:latest .
